# Proxmox authentication
proxmox_url = "https://edge-pve-01.lan.homelab:8006/api2/json"

# Clone
clone_vm = "ubuntu-24-04-desktop-raw"

# General
node                 = "edge-pve-01"
vm_id                = 931
vm_name              = "ubuntu-24-04-desktop-standard"
pool                 = "Template"
template_description = "Ubuntu desktop 24.04 template with the default configuration generated by Packer on {{ isotime `2006-01-02 15:04` }}."

# Cloud-Init
cloud_init_storage_pool = "Ceph_Gold"
