clone_vm = "ubuntu-22-04-desktop-raw"

vm_id                = 903
vm_name              = "ubuntu-22-04-desktop-standard"
template_description = "Ubuntu desktop 22.04 template with the default configuration generated by Packer on {{ isotime `2006-01-02` }}."