proxmox_url          = "https://pve-02.lan.homelab:8006/api2/json"
node                 = "pve-02"
vm_id                = 931
build_name           = "ubuntu"
vm_name              = "ubuntu-24-04-desktop-standard"
clone_vm             = "ubuntu-24-04-desktop-raw"
template_description = "Ubuntu desktop 24.04 template with the default configuration generated by Packer on {{ isotime `2006-01-02` }}."

vga = {
  type   = "std",
  memory = 32
}
