proxmox_url = "https://pve-01.homelab:8006/api2/json"
node        = "pve-02"

clone_vm = "ubuntu-22-04-desktop-raw"

vm_id                = 931
build_name           = "ubuntu"
vm_name              = "ubuntu-22-04-desktop-standard"
template_description = "Ubuntu desktop 22.04 template with the default configuration generated by Packer on {{ isotime `2006-01-02` }}."

vga = {
  type   = "std",
  memory = 32
}
