---
- name: "Searching for files that can be removed"
  ansible.builtin.find:
    paths:
      - "/var/log"
      - "/var/tmp"
      - "/tmp"
    patterns: "*"
    recurse: true
  register: "files_to_delete"

- name: "Removing unnecessary files"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "absent"
  loop: "{{ files_to_delete.files }}"
  loop_control:
    index_var: "index"
    label: "{{ index }} - {{ item.path }}"
