---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      - {name: "sshpass"} # noninteractive ssh password provider.
      - {name: "libsecret-tools"} # Store and retrieve passwords.
      - {name: "traceroute"} # It helps debug network problems.
      - {name: "whois"} # To enable mkpasswd command.
      - {name: "net-tools"} # A collection of programs that form the base set of the NET-3 networking.
      - {name: "tree"} # List contents of directories in a tree-like format.
      - {name: "uuid"} # Universally Unique Identifier Command-Line Tool.
      - {name: "fail2ban"} # Is an intrusion prevention software framework.
      - {name: "nikto"} # To run vulnerabilidade scans.
      - {name: "xrdp"} # To enable Microsoft Remote Connection.
      - {name: "chrome-gnome-shell"} # To enable Microsoft Remote Connection multiple logins.
      - {name: "xclip"} # Copy to clipboard.
      - {name: "dbus-x11"} # Required for the community.general.dconf module.
      - {name: "ethtool"} # To enable Wake-on-Lan.
      - {name: "curl"} # Transfer a URL.
      - {name: "rsyslog"}
      - {name: "git"}
      - {name: "ufw"} # A program for managing the firewall for the VM.
      - {name: "gnupg2"} # To use GPG.

- name: "Installing pip packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/pip.yml"
  vars:
    packages:
      - {name: "ansible"}
      - {name: "ansible-lint"}
      - {name: "psutil"} # Required for the community.general.dconf module.
      - {name: "passlib"} # Required to use bcrypt.
      - {name: "jmespath"} # Required to use json_query.

- name: "Installing all the required collections"
  community.general.ansible_galaxy_install:
    type: "collection"
    name: "{{ item }}"
  loop:
    - "community.general" # To work with dconf.

- name: "Setting up XClip"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/xclip.yml"

- name: "Setting up Google Chrome"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/google-chrome.yml"

- name: "Setting up VSCode"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/vscode.yml"

- name: "Setting up HashiCorp packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/hashicorp.yml"

- name: "Setting up XRDP"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/xrdp.yml"
