---
- name: "Installing required packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    update_cache: true
    upgrade: "safe"
    packages:
      # Desktop Essentials - Core packages for desktop functionality and remote access.
      - {name: "xrdp"} # Allows remote desktop connections using Microsoft RDP.
      - {name: "libvirglrenderer1"} # Enables virtio-gl GPU acceleration.
      - {name: "dbus-x11"} # D-Bus support for X applications; required by community.general.dconf.
      - {name: "xclip"} # Accesses the X clipboard from the command line.
      - {name: "chrome-gnome-shell"} # Enables GNOME Shell integration for Chrome.
      # Security and Access - Tools for securing the VM and managing access.
      - {name: "ufw"} # Manages firewall rules with Uncomplicated Firewall.
      - {name: "fail2ban"} # Protects against brute-force attacks.
      - {name: "gnupg2"} # For encryption and signing using GPG.
      - {name: "libsecret-tools"} # Stores and retrieves passwords securely.
      - {name: "sshpass"} # For non-interactive SSH password entry.
      # Networking and Diagnostics - Tools for network management and diagnostics.
      - {name: "ethtool"} # Manages network device settings, including Wake-on-LAN.
      - {name: "net-tools"} # Networking utilities (ifconfig, netstat).
      - {name: "traceroute"} # For diagnosing network routing issues.
      - {name: "whois"} # Retrieves domain and IP information.
      - {name: "curl"} # Transfers data with URLs.
      # System Utilities and Logging - Tools for system management and logging.
      - {name: "rsyslog"} # Provides system logging service.
      - {name: "tree"} # Displays directory contents in a tree-like format.
      - {name: "uuid"} # Generates Universally Unique Identifiers (UUIDs).
      # Development Tools - Tools for development and Python-related functionality.
      - {name: "git"} # Version control system for tracking changes in source code.
      - {name: "pipx"} # Installs and runs Python apps in isolated environments.
      - {name: "python3-psutil"} # Retrieves system/process info; required by community.general.dconf.
      - {name: "python3-passlib"} # Password hashing library with bcrypt support.
      - {name: "python3-jmespath"} # Queries JSON data using JMESPath expressions.
      # Specialized Tools - Additional tools for specific tasks.
      - {name: "nikto"} # Web server scanner for detecting vulnerabilities.
      - {name: "restic"} # Efficient and secure backup program.

- name: "Setting up XClip"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/xclip.yml"

- name: "Setting up Google Chrome"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/google-chrome.yml"

- name: "Setting up VSCode"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/vscode.yml"

- name: "Setting up HashiCorp packages"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/hashicorp.yml"

- name: "Setting up the Docker"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/docker.yml"

- name: "Setting up XRDP"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/xrdp.yml"
