---
- name: "Changing the hostname"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/hostname.yml"

- name: "Installing required packages"
  ansible.builtin.import_tasks: "installing-packages.yml"

- name: "Setting up the Firewall UFW"
  ansible.builtin.import_tasks: "ufw.yml"

- name: "Setting up fail2ban"
  ansible.builtin.import_tasks: "fail2ban.yml"

- name: "Copying the unlock-keyring function"
  ansible.builtin.import_tasks: "unlock-keyring.yml"

- name: "Adding the favorite applications in the Dock"
  ansible.builtin.import_tasks: "adding-favorite-apps-to-dock.yml"

- name: "Setting the dark theme"
  ansible.builtin.import_tasks: "dark-theme.yml"

- name: "Removing unnecessary packages"
  ansible.builtin.import_tasks: "removing-packages.yml"

- name: "Recreating the machine-id file so the new VM can get a new IP"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/machine-id.yml"

- name: "Removing unnecessary files, folders and configuration"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/clean-up.yml"
