---
- name: "Removing snap applications"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/snap.yml"
  vars:
    packages:
      - {name: "firefox", state: "absent"}
      - {name: "apport", state: "absent", purge: true}
      - {name: "openvpn", state: "absent", purge: true}

- name: "Removing dependencies that are no longer required and unnecessary packages from the cache"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/packages/apt.yml"
  vars:
    autoremove: true
    autoclean: true
